export { ReactComponent as Home } from '@assets/icons/Home.svg'
export { ReactComponent as Schedule } from '@assets/icons/Schedule.svg'
export { ReactComponent as Member } from '@assets/icons/Member.svg'
export { ReactComponent as Center } from '@assets/icons/Center.svg'
export { ReactComponent as Mypage } from '@assets/icons/Mypage.svg'