export { ReactComponent as Home } from '@assets/icons/Home.svg';
export { ReactComponent as Schedule } from '@assets/icons/Schedule.svg';
export { ReactComponent as Member } from '@assets/icons/Member.svg';
export { ReactComponent as Center } from '@assets/icons/Center.svg';
export { ReactComponent as Mypage } from '@assets/icons/Mypage.svg';
export { ReactComponent as Notifications } from '@assets/icons/Notifications.svg';
export { ReactComponent as TicketIcon } from '@assets/icons/ticket/ticketIcon.svg';
export { ReactComponent as MemberIcon } from '@assets/icons/memberIcon.svg';
export { ReactComponent as BackIcon } from '@assets/icons/backIcon.svg';
